In [1]:
from functions.get_function_setting import get_function_setting
from algorithms import ParticleSwarmOptimization
from numpy import mean, median, std

In [2]:
# number_iteration: 500
for number in range(1, 7+1, 1):
    function_setting = get_function_setting(number)

    # parameter setting
    number_iteration = 500
    number_particle = 50
    boundaries = [function_setting["boundary"]] * function_setting["dimension"]

    best_fitnesses = []
    solutions = []
    for _ in range(50):
        particle_swarm_optimization = \
            ParticleSwarmOptimization(
                function_setting["function"],
                boundaries,
                number_iteration,
                number_particle,
                exploration_acceleration=1,
                exploitation_acceleration=1
            )

        particle_swarm_optimization.optimize()
        best_fitnesses.append(particle_swarm_optimization.best_fitness) # PSO best fitness
        solutions.append([particle_swarm_optimization.particles[index].position for index in range(number_particle)])


    # print(f"Best fitness of function {number} is: {min(best_fitnesses)}")
    print("-" * 20)
    print(f"Average Fitness: {mean(best_fitnesses)}")
    print(f"Median Fitness: {median(best_fitnesses)}")
    print(f"Average solution: {mean(solutions, axis=0)}")
    print(f"Standard Deviation of solution: {std(solutions ,axis=0)}")

--------------------
Average Fitness: 40.83471120890488
Median Fitness: 39.796340497426414
Average solution: [[-0.45377499  0.45668908 -0.19997775 ...  0.40040769  0.43106821
  -0.16958743]
 [ 0.10933697  0.3365329  -0.43444667 ...  0.08722061  0.14351025
  -0.53288747]
 [-0.11195963  0.01718143 -0.51056645 ...  0.28738596  0.27248322
   0.08529428]
 ...
 [ 0.00983138  0.3433007  -0.37320309 ...  0.15302858  0.08836479
  -0.25680881]
 [ 0.07595688  0.66595799 -0.60105159 ...  0.29080785  0.17784823
  -0.08821199]
 [ 0.41592795  0.1565873  -0.18382615 ...  0.4056404   0.09037022
  -0.14967919]]
Standard Deviation of solution: [[2.15746215 2.07970098 1.84593775 ... 1.79617472 1.87504069 1.90147473]
 [2.15260109 2.25037871 2.0741646  ... 1.55866125 2.02860575 1.80913802]
 [1.91696435 1.92482544 2.3913614  ... 1.9145382  1.97177814 2.03955188]
 ...
 [2.23968433 1.96226381 2.26772653 ... 1.74097349 2.05416867 2.28046419]
 [2.06456463 2.02082555 2.3415392  ... 2.07337923 2.02822468 1.7732343